### ISSUE TITLE
Error extracting subtomos 

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-dynamo#82]
After a the model workflow and the former vectorial picker the subprogram extraction fails:

See project in alter5 
Project pickingvesicles

![image](https://github.com/scipion-em/scipion-em-dynamo/assets/12271438/1c8dc9c5-99b7-4607-bec3-fc88e75c0683)

![image](https://github.com/scipion-em/scipion-em-dynamo/assets/12271438/c6a91778-e211-4360-9e4e-13ed601318c6)

**Comment by JorMaister** [comment]
Hi, @Vilax, what's the project name?

**Comment by Vilax** [comment]
Updated the report. 

Project: pickingvesicles
